# Generated by Django 3.2.7 on 2021-10-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_post_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover',
        ),
    ]
